package com.mycompany.traductorarduino;

import javax.swing.*;
import java.awt.*;
import java.awt.datatransfer.StringSelection;


public class Gui extends javax.swing.JFrame {
    

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        traductor = new Traductor();
        
        setTitle("Traductor Arduino");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new Dimension(1000, 474));
        textAreaCodigoArduino.setText(
                "Lenguaje Pilot:\n" +
                "Utilice las palabaras claves: NORTE(), OESTE(), ESTE() para programar el recorrido de su" +
                " carrito. En los parentesis incluya cuantos pasos debe dar..."
        );
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonTraducir = new javax.swing.JButton();
        botonCopiar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaCodigoPilot = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaCodigoArduino = new javax.swing.JTextArea();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        botonTraducir.setIcon(new javax.swing.ImageIcon("C:\\Users\\samue\\OneDrive - Universidad Mariano Gálvez\\Escritorio\\TraductorArduino\\src\\main\\java\\com\\mycompany\\traductorarduino\\resources\\play.png")); // NOI18N
        botonTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTraducirActionPerformed(evt);
            }
        });
        jPanel2.add(botonTraducir);

        botonCopiar.setIcon(new javax.swing.ImageIcon("C:\\Users\\samue\\OneDrive - Universidad Mariano Gálvez\\Escritorio\\TraductorArduino\\src\\main\\java\\com\\mycompany\\traductorarduino\\resources\\notes.png")); // NOI18N
        botonCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCopiarActionPerformed(evt);
            }
        });
        jPanel2.add(botonCopiar);
        jPanel2.add(filler1);
        jPanel2.add(filler2);
        jPanel2.add(filler3);
        jPanel2.add(filler4);
        jPanel2.add(filler5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 283;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 12);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        textAreaCodigoPilot.setColumns(20);
        textAreaCodigoPilot.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        textAreaCodigoPilot.setRows(5);
        jScrollPane3.setViewportView(textAreaCodigoPilot);

        jPanel3.add(jScrollPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 793;
        gridBagConstraints.ipady = 99;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 12);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        textAreaCodigoArduino.setColumns(20);
        textAreaCodigoArduino.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        textAreaCodigoArduino.setRows(5);
        jScrollPane4.setViewportView(textAreaCodigoArduino);

        jPanel6.add(jScrollPane4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 793;
        gridBagConstraints.ipady = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 12, 12);
        jPanel1.add(jPanel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(filler6, gridBagConstraints);

        getContentPane().add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void botonTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTraducirActionPerformed
        // TODO add your handling code here:
        String codigo = textAreaCodigoPilot.getText();
        traductor.getTokensValidos(codigo);
        String codigoArduino = traductor.getArduino();
        textAreaCodigoArduino.setText(codigoArduino);
        StringSelection codigoCopia = new StringSelection(codigoArduino);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(codigoCopia, null);
    }//GEN-LAST:event_botonTraducirActionPerformed

    private void botonCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCopiarActionPerformed
        // TODO add your handling code here:
        String codigoArduino = textAreaCodigoArduino.getText();
        StringSelection codigo = new StringSelection(codigoArduino);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(codigo, null);
    }//GEN-LAST:event_botonCopiarActionPerformed

public static void main(String[] args) {
        // Schedule the GUI creation on the Event Dispatch Thread
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                Gui frame = new Gui();
                frame.setVisible(true);
            }
        });
    }
    public Traductor traductor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCopiar;
    private javax.swing.JButton botonTraducir;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea textAreaCodigoArduino;
    private javax.swing.JTextArea textAreaCodigoPilot;
    // End of variables declaration//GEN-END:variables
}
