/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.traductorarduino;

import java.awt.Dimension;

/**
 *
 * @author samue
 */
public class Tokens extends javax.swing.JDialog {

    /**
     * Creates new form Tokens
     */
    public Tokens(java.awt.Frame parent, boolean modal, String tokens) {
        super(parent, modal);
        initComponents();
        setMinimumSize(new Dimension(1000, 474));
        setLocationRelativeTo(null);
        setTitle("Tokens");
        textAreaTokens.setText(tokens);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaTokens = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        textAreaTokens.setColumns(20);
        textAreaTokens.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        textAreaTokens.setRows(5);
        jScrollPane1.setViewportView(textAreaTokens);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaTokens;
    // End of variables declaration//GEN-END:variables
}
